name: Build box2d Libraries

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x86_64
          - os: windows-latest
            arch: x86
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        repository: 'erincatto/box2d'
        path: 'box2d'
        submodules: true
        ref: 'v3.0.0'

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure box2d with CMake for macOS ARM64
      if: matrix.arch == 'arm64' && matrix.os == 'macos-latest'
      run: cmake -S box2d -B box2d/build -DCMAKE_OSX_ARCHITECTURES=arm64

    - name: Configure box2d with CMake
      if: matrix.arch != 'arm64' || matrix.os != 'macos-latest'
      run: cmake -S box2d -B box2d/build

    - name: Build box2d
      run: cmake --build box2d/build --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-artifacts 
        path: |
          box2d/build/bin/Release/*.dll
          box2d/build/bin/*.so
          box2d/build/bin/*.dylib
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'
